# Site settings
encoding: utf-8
title: Sophialuu-blog
description: Sophialuu的个人博客
baseurl: "https://lujiayan.github.io/blog/" 
# baseurl: ''
github_username:  Sophialuu
paginate: 8
paginate_path: "/page:num"
footer_twitter: "Twitter"
footer_twitter_site: "https://github.com/LuJIAYan"
footer_github: "GitHub"
footer_github_site: "https://github.com/LuJIAYan"
footer_resume: "简历"
footer_resume_site: "https://github.com/LuJIAYan"
port: 8070
gems: [jekyll-paginate]
